### ISSUE TITLE
Untyped nils need not cause a panic

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/tf#5]
Untyped nils need to be cast, like:

```go
MyFunction(nil).Returns("foo") // will not work
MyFunction((MyStruct*)(nil)).Returns("foo") // works
```

Internally it should determine and cast the correct type of nil so that the caller doesn't have to worry about this.

**Comment by m1ome** [comment]
This should be solved now, apart #11 (this one also handles nils in return statements)

**Comment by m1ome** [comment]
@elliotchance this this one is solved now 🎆

**Comment by elliotchance** [comment]
Thank you very much @m1ome !
